### ISSUE TITLE
Get the invalid candidates for the file path if set the "forceCompletionPattern: '/'"

### ISSUE THREAD

**Issue by shun** [shun/ddc-vim-lsp#2]
After set  "forceCompletionPattern: '/'", get the invalid candidates for the file path.
Should be distinguished the file path or not.

<img width="311" alt="image" src="https://user-images.githubusercontent.com/212602/128822366-b1833d70-0a97-49fd-a365-c85d304cc1a4.png">

**Comment by Shougo** [comment]
I think it is better.

`'nvimlsp': {'mark': 'nvimlsp', 'forceCompletionPattern': '\.|:|->|"\w*/'`

**Comment by shun** [comment]
@Shougo 
Thanks for your advice and it's much better !!

But I think it's better to distinguish the delimiter for each filetype.
Therefore, plugin should change the delimiter dynamically in my opinion.

I'm keep investigating this issue what is the better solution.

Thank you.

**Comment by Shougo** [comment]
You can change it by filetype.

```vim
call ddc#custom#patch_filetype(['go'], 'sourcesOptions'
\ { 'vimlsp': {'mark': 'vimlsp', 'forceCompletionPattern': '\.|:|->|"\w*/' })
```

**Comment by shun** [comment]
@Shougo 
This is the solution which I want.
Should be enough for me.

I close this.
Thank you !

**Comment by Shougo** [comment]
deoplete has not the feature.
So ddc.vim is better than deoplete!
