### ISSUE TITLE
[Bug] Other sources die when language server is stopping

### ISSUE THREAD

**Issue by kuuote** [shun/ddc-vim-lsp#3]
[Bug] Other sources die when language server is stopping

# Description
If you use this plugin with other `ddc` sources and when language server is stopped, other sources die.

# Reproduce Step
1. Install below plugins.

```
https://github.com/vim-denops/denops.vim
https://github.com/Shougo/ddc.vim
https://github.com/Shougo/ddc-around
https://github.com/shun/ddc-vim-lsp
https://github.com/prabirshrestha/vim-lsp
https://github.com/mattn/vim-lsp-settings
```

2. Write below vimrc.

```vim
filetype plugin indent on
syntax on
packloadall! " if install with package

call ddc#custom#patch_global('sources', ['around', 'ddc-vim-lsp'])
call ddc#enable()
```

3. Type it.

```
hoge
hoge
```

# Expected behavior
Shows `around` text completion at second line.

# Environment
Arch Linux
Vim 8.2.3346
Deon 1.13.0

**Comment by shun** [comment]
This issue fixed by this commit [04f86a1a](https://github.com/shun/ddc-vim-lsp/commit/04f86a1aa553258e22988b64253ef44c849c5b21).

Thanks for you report !
